/**
 * Game_Page_v1.js
 * Logic for the Educational Image Compression Game (Professional Version)
 */

// ==========================================
// 1. Global State & DOM Elements
// ==========================================
const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d', { willReadFrequently: true });
const imageLoader = document.getElementById('imageLoader');
const uploadUI = document.getElementById('upload-ui');

// Metric Displays
const scoreDisplay = document.getElementById('score-display');
const timeDisplay = document.getElementById('time-display');
const psnrDisplay = document.getElementById('psnr-display');
const ssimDisplay = document.getElementById('ssim-display');
const sizePercentage = document.getElementById('size-percentage');
const progressBarFill = document.getElementById('progress-bar-fill');
const feedbackMsg = document.getElementById('feedback-msg');

// Game State
let originalImage = null;
let currentMode = 'compression';
let gameTimer = null;
let secondsElapsed = 0;
let isPlaying = false;
let baseFileSize = 100000; // Mock base size for calculations

// RLE Specific State
let rleDifficulty = 'Easy';

// ==========================================
// 2. Game Mode Configurations
// ==========================================
const MODE_DATA = {
  compression: {
    title: "Compression Challenge",
    instructions: `
            <p style="margin-bottom: 15px;">Welcome to the Compression Challenge! Balance size and quality.</p>
            <ul>
                <li>Upload your image to start.</li>
                <li>Adjust the compression quality slider.</li>
                <li>Aim for the lowest size while keeping PSNR above 30dB!</li>
            </ul>`,
    controlsHtml: `
            <label>JPEG Quality Level:</label>
            <div class="slider-container">
                <span>Low (Blocky)</span>
                <input type="range" id="quality-slider" min="1" max="100" value="80" oninput="handleCompressionChange(this.value)">
                <span>High (Clear)</span>
            </div>`
  },
  rle: {
    title: "RLE Puzzle (Run-Length Encoding)",
    instructions: `
            <p style="margin-bottom: 15px;">Compress the data manually!</p>
            <ul>
                <li>Look at the sequence of colored blocks above.</li>
                <li>Count how many consecutive blocks of the same color there are.</li>
                <li>Input the number and select the color below.</li>
                <li>Hit Compress and watch the space shrink!</li>
            </ul>`,
    // Control area will be dynamically generated by JS
    controlsHtml: `<div id="rle-inputs-container"></div>`
  },
  dct: {
    title: "Advanced DCT Control",
    instructions: `
            <p style="margin-bottom: 15px;">DCT separates images into frequency components.</p>
            <ul>
                <li>High frequencies contain sharp edges and details.</li>
                <li>Low frequencies contain general colors and shapes.</li>
                <li>Cut high frequencies to save space (causes blurriness).</li>
            </ul>`,
    controlsHtml: `
            <label>Cut High Frequencies (Low-Pass Filter):</label>
            <div class="slider-container">
                <span>Keep All</span>
                <input type="range" id="dct-slider" min="0" max="20" value="0" step="1" oninput="handleDCTChange(this.value)">
                <span>Heavy Cut</span>
            </div>`
  }
};

// ==========================================
// 3. Image Upload & Canvas Rendering
// ==========================================
imageLoader.addEventListener('change', handleImageUpload);

function handleImageUpload(e) {
  const reader = new FileReader();
  reader.onload = function(event) {
    const img = new Image();
    img.onload = function() {
      originalImage = img;
      uploadUI.style.display = 'none';
      canvas.style.display = 'block';

      // Resize canvas to fit container while maintaining aspect ratio
      const container = canvas.parentElement;
      const maxWidth = container.clientWidth - 20;
      const maxHeight = container.clientHeight - 20;

      let width = img.width;
      let height = img.height;

      if (width > maxWidth) {
        height *= maxWidth / width;
        width = maxWidth;
      }
      if (height > maxHeight) {
        width *= maxHeight / height;
        height = maxHeight;
      }

      canvas.width = width;
      canvas.height = height;

      // Draw initial image
      resetCanvas();
      startGame();
    }
    img.src = event.target.result;
  }
  if(e.target.files[0]) {
    baseFileSize = e.target.files[0].size;
    reader.readAsDataURL(e.target.files[0]);
  }
}

function resetCanvas() {
  if (!originalImage) return;
  ctx.filter = 'none'; // Clear filters
  ctx.drawImage(originalImage, 0, 0, canvas.width, canvas.height);
}

// ==========================================
// 4. Tab Switching Logic
// ==========================================
function switchMode(mode, event) {
  currentMode = mode;
  const data = MODE_DATA[mode];

  // Update Tab highlight
  document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
  if (event) event.target.classList.add('active');

  // Update basic text
  document.getElementById('page-title').innerText = data.title;
  document.getElementById('instruction-content').innerHTML = data.instructions;

  const rleVisualArea = document.getElementById('rle-visual-area');
  const canvasDOM = document.getElementById('gameCanvas');
  const uploadDOM = document.getElementById('upload-ui');
  const metricsBox = document.querySelector('.metrics-box');
  const bottomControls = document.querySelector('.game-panel > .controls');

  // Reset global timer when switching modes
  pauseGame();
  secondsElapsed = 0;
  timeDisplay.innerText = "00:00";

  if (mode === 'rle') {
    canvasDOM.style.display = 'none';
    uploadDOM.style.display = 'none';
    rleVisualArea.style.display = 'flex';

    // Hide general metrics and bottom controls for RLE
    if (metricsBox) metricsBox.style.display = 'none';
    if (bottomControls) bottomControls.style.display = 'none';

    showRLEStartScreen(); // Show start screen
  } else {
    rleVisualArea.style.display = 'none';

    // Restore general metrics and bottom controls
    if (metricsBox) metricsBox.style.display = 'flex';
    if (bottomControls) bottomControls.style.display = 'flex';

    if (originalImage) {
      canvasDOM.style.display = 'block';
      uploadDOM.style.display = 'none';
    } else {
      canvasDOM.style.display = 'none';
      uploadDOM.style.display = 'block';
    }

    resetCanvas();
    if (originalImage) {
      if (mode === 'compression') handleCompressionChange(80);
      if (mode === 'dct') handleDCTChange(0);
      startGame();
    }
  }
}

// ==========================================
// 5. RLE Puzzle Logic & Audio
// ==========================================

const RLE_COLORS = [
  { name: 'Red', hex: '#ff4757' },
  { name: 'Blue', hex: '#1e90ff' },
  { name: 'Green', hex: '#2ed573' }
];

let currentRLEAnswer = [];
let totalOriginalBlocks = 0;

// Synthesize 'ding' sound using native Web Audio API
function playSuccessSound() {
  const AudioContext = window.AudioContext || window.webkitAudioContext;
  if (!AudioContext) return;
  const ctx = new AudioContext();
  const osc = ctx.createOscillator();
  const gainNode = ctx.createGain();

  osc.type = 'sine';
  osc.frequency.setValueAtTime(880, ctx.currentTime);
  osc.frequency.exponentialRampToValueAtTime(1760, ctx.currentTime + 0.1);

  gainNode.gain.setValueAtTime(0, ctx.currentTime);
  gainNode.gain.linearRampToValueAtTime(0.5, ctx.currentTime + 0.05);
  gainNode.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.5);

  osc.connect(gainNode);
  gainNode.connect(ctx.destination);
  osc.start();
  osc.stop(ctx.currentTime + 0.5);
}

function showRLEStartScreen() {
  pauseGame(); // Ensure global timer is stopped on start screen

  const area = document.getElementById('rle-visual-area');
  area.innerHTML = `
        <div class="rle-start-screen">
            <h2 style="color: #2c3e50;">RLE Challenge</h2>
            <p>Pick your difficulty to begin the timer!</p>
            <div class="difficulty-group">
                <button class="diff-btn easy ${rleDifficulty==='Easy'?'selected':''}" onclick="setRleDifficulty('Easy')">Easy</button>
                <button class="diff-btn medium ${rleDifficulty==='Medium'?'selected':''}" onclick="setRleDifficulty('Medium')">Medium</button>
                <button class="diff-btn hard ${rleDifficulty==='Hard'?'selected':''}" onclick="setRleDifficulty('Hard')">Hard</button>
            </div>
            <button class="btn-primary" style="font-size: 24px; padding: 15px 50px; margin-top: 20px;" onclick="startRLEChallenge()">
                ▶ START CHALLENGE
            </button>
        </div>
    `;
  document.getElementById('specific-controls').innerHTML = '';
}

function setRleDifficulty(diff) {
  rleDifficulty = diff;
  showRLEStartScreen(); // Refresh selected state
}

// Actual start after clicking START
function startRLEChallenge() {
  // 1. Reset Global Timer and Score
  pauseGame();
  secondsElapsed = 0;
  timeDisplay.innerText = "00:00";
  scoreDisplay.innerText = "1000";

  // 2. Prepare game interface structure (Removed inner timer)
  const area = document.getElementById('rle-visual-area');
  area.innerHTML = `
        <h3 style="margin-bottom: 20px; color: #2c3e50; text-align: center;">Original Sequence</h3>
        <div id="rle-blocks-container" class="rle-blocks-container"></div>
    `;

  // 3. Generate challenge based on difficulty
  initRLEPuzzleWithDifficulty(rleDifficulty);

  // 4. Start the Global Timer
  startGame();
}

function initRLEPuzzleWithDifficulty(diff) {
  // Define strict targets: Total Blocks and Segment Counts
  let targetTotal = 10; // Easy: 1 row
  let segmentCount = 3;

  if (diff === 'Medium') { targetTotal = 20; segmentCount = 5; } // Medium: 2 rows
  if (diff === 'Hard') { targetTotal = 40; segmentCount = 8; } // Hard: 4 rows

  const blocksContainer = document.getElementById('rle-blocks-container');

  // Apply dynamic Grid layout to strictly enforce 10 blocks per row
  blocksContainer.style.display = 'grid';
  blocksContainer.style.gridTemplateColumns = 'repeat(10, 40px)';
  blocksContainer.style.gap = '8px 5px';
  blocksContainer.style.justifyContent = 'center';
  blocksContainer.style.margin = '0 auto';
  blocksContainer.style.padding = '20px';
  blocksContainer.style.background = '#f8f9fa';
  blocksContainer.style.borderRadius = '10px';
  blocksContainer.style.boxShadow = 'inset 0 2px 4px rgba(0,0,0,0.1)';
  blocksContainer.style.width = 'max-content';

  const controlsContainer = document.getElementById('specific-controls');
  controlsContainer.innerHTML = '<div id="rle-inputs-container"></div>';
  const inputsContainer = document.getElementById('rle-inputs-container');

  currentRLEAnswer = [];
  totalOriginalBlocks = targetTotal;

  // Exact block partitioning logic: Ensure sum of counts exactly equals targetTotal
  let counts = Array(segmentCount).fill(1); // Give each segment at least 1 block
  let remaining = targetTotal - segmentCount;

  while(remaining > 0) {
    let idx = Math.floor(Math.random() * segmentCount);
    // Optional cap to prevent a single color segment from dominating
    if (counts[idx] < 12) {
      counts[idx]++;
      remaining--;
    }
  }

  // Generate blocks based on the exact partitioning
  let lastColorIndex = -1;
  for (let i = 0; i < segmentCount; i++) {
    let colorIndex;
    do { colorIndex = Math.floor(Math.random() * RLE_COLORS.length); } while (colorIndex === lastColorIndex);
    lastColorIndex = colorIndex;

    const count = counts[i];
    const colorObj = RLE_COLORS[colorIndex];

    currentRLEAnswer.push({ count: count, color: colorObj.name });

    // Render Blocks
    for (let j = 0; j < count; j++) {
      const block = document.createElement('div');
      block.className = 'rle-block';
      block.style.backgroundColor = colorObj.hex;
      block.dataset.segment = i;
      blocksContainer.appendChild(block);
    }

    // Render Input Fields
    const inputGroup = document.createElement('div');
    inputGroup.className = 'rle-input-group';
    inputGroup.innerHTML = `
            <input type="number" placeholder="#" id="rle-num-${i}">
            <span> x </span>
            <select id="rle-color-${i}">
                <option value="">Color...</option>
                ${RLE_COLORS.map(c => `<option value="${c.name}">${c.name}</option>`).join('')}
            </select>
        `;
    inputsContainer.appendChild(inputGroup);
  }

  // ==== Build Button Group ====
  const actionGroup = document.createElement('div');
  actionGroup.className = 'rle-action-group';

  // Main compress button
  const compressBtn = document.createElement('button');
  compressBtn.className = 'controls button rle-check-btn';
  compressBtn.id = 'rle-compress-btn';
  compressBtn.innerHTML = '🗜️ Compress Data!';
  compressBtn.onclick = checkRLEPuzzle;
  actionGroup.appendChild(compressBtn);

  // Helper row (Back to menu & Show answer)
  const helperRow = document.createElement('div');
  helperRow.className = 'rle-helper-row';
  helperRow.id = 'rle-helper-row';

  const backBtn = document.createElement('button');
  backBtn.className = 'rle-secondary-btn';
  backBtn.innerHTML = '⬅️ Back to Menu';
  backBtn.onclick = () => {
    showRLEStartScreen();
  };

  const answerBtn = document.createElement('button');
  answerBtn.className = 'rle-secondary-btn';
  answerBtn.id = 'rle-answer-btn';
  answerBtn.innerHTML = '💡 Show Answer';
  answerBtn.onclick = showRLEAnswer;

  helperRow.appendChild(backBtn);
  helperRow.appendChild(answerBtn);
  actionGroup.appendChild(helperRow);

  inputsContainer.appendChild(actionGroup);

  // Reset metrics
  updateMetricsUI(100, "Perfect", "1.00", 100);
  feedbackMsg.innerText = "Count the blocks and compress!";
  feedbackMsg.style.color = "#7f8c8d";
}

function checkRLEPuzzle() {
  let isCorrect = true;

  // Check user input
  for (let i = 0; i < currentRLEAnswer.length; i++) {
    const userNum = parseInt(document.getElementById(`rle-num-${i}`).value);
    const userColor = document.getElementById(`rle-color-${i}`).value;

    if (userNum !== currentRLEAnswer[i].count || userColor !== currentRLEAnswer[i].color) {
      isCorrect = false;
      break;
    }
  }

  if (!isCorrect) {
    feedbackMsg.style.color = "#e74c3c";
    feedbackMsg.innerText = "Oops! Check your numbers and colors again.";
    document.getElementById('rle-inputs-container').animate([
      { transform: 'translateX(0)' }, { transform: 'translateX(-10px)' },
      { transform: 'translateX(10px)' }, { transform: 'translateX(0)' }
    ], { duration: 300 });
    return;
  }

  // === Correct answer ===
  pauseGame(); // Stop Global Timer
  playSuccessSound();
  feedbackMsg.style.color = "#2ecc71";
  feedbackMsg.innerText = "Awesome! Data successfully compressed via RLE!";

  const blocksContainer = document.getElementById('rle-blocks-container');

  // Switch layout from strict Grid to Flex to allow smooth squeezing animation
  blocksContainer.style.display = 'flex';
  blocksContainer.style.flexWrap = 'wrap';

  // Execute merge animation
  for (let i = 0; i < currentRLEAnswer.length; i++) {
    const segmentBlocks = blocksContainer.querySelectorAll(`.rle-block[data-segment="${i}"]`);

    segmentBlocks.forEach((block, index) => {
      if (index > 0) {
        block.style.width = '0px';
        block.style.margin = '0px';
        block.style.opacity = '0';
        block.style.padding = '0px';
        block.style.overflow = 'hidden';
      } else {
        block.classList.add('merged');
        block.innerText = `${currentRLEAnswer[i].count}x`;
      }
    });
  }

  const compressedBlocksCount = currentRLEAnswer.length;
  const sizeRatio = Math.floor((compressedBlocksCount / totalOriginalBlocks) * 100);

  setTimeout(() => {
    updateMetricsUI(sizeRatio, "Perfect", "1.00", 100);
  }, 500);

  // Disable inputs
  document.querySelectorAll('.rle-input-group input, .rle-input-group select').forEach(el => el.disabled = true);

  const compressBtn = document.getElementById('rle-compress-btn');
  compressBtn.innerText = "🔄 Play Again (Same Difficulty)";
  compressBtn.onclick = () => startRLEChallenge(); // Auto-restart timer

  const answerBtn = document.getElementById('rle-answer-btn');
  if (answerBtn) answerBtn.style.display = 'none';

  const helperRow = document.getElementById('rle-helper-row');
  if(helperRow) {
    const backBtn = helperRow.querySelector('button');
    backBtn.innerHTML = '⬅️ Change Difficulty';
  }
}

function showRLEAnswer() {
  pauseGame(); // Stop Global Timer

  for (let i = 0; i < currentRLEAnswer.length; i++) {
    document.getElementById(`rle-num-${i}`).value = currentRLEAnswer[i].count;
    document.getElementById(`rle-color-${i}`).value = currentRLEAnswer[i].color;
  }

  feedbackMsg.style.color = "#f39c12";
  feedbackMsg.innerText = "Answer revealed. The timer has stopped. Try another one!";

  document.querySelectorAll('.rle-input-group input, .rle-input-group select').forEach(el => el.disabled = true);

  const compressBtn = document.getElementById('rle-compress-btn');
  compressBtn.innerText = "🔄 Try Another Puzzle";
  compressBtn.style.backgroundColor = "#f39c12";
  compressBtn.onclick = () => {
    compressBtn.style.backgroundColor = "";
    startRLEChallenge();
  };

  const answerBtn = document.getElementById('rle-answer-btn');
  if (answerBtn) answerBtn.style.display = 'none';
}


// ==========================================
// 6. Core Game Logic & Simulations (Other Modes)
// ==========================================

function handleCompressionChange(quality) {
  if (!originalImage) return;
  resetCanvas();

  const qualityLevel = quality / 100;

  const compressedDataUrl = canvas.toDataURL('image/jpeg', qualityLevel);
  const img = new Image();
  img.onload = () => {
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

    const sizeRatio = Math.max(10, Math.floor(qualityLevel * 85 + 15));
    const psnr = (20 + (qualityLevel * 25)).toFixed(1);
    const ssim = (0.50 + (qualityLevel * 0.49)).toFixed(2);

    updateMetricsUI(sizeRatio, psnr, ssim, quality);
  };
  img.src = compressedDataUrl;
}

function handleDCTChange(blurAmount) {
  if (!originalImage) return;

  ctx.filter = `blur(${blurAmount}px)`;
  ctx.drawImage(originalImage, 0, 0, canvas.width, canvas.height);

  const sizeRatio = Math.max(15, 100 - (blurAmount * 4));
  const psnr = Math.max(15, (40 - blurAmount * 1.5)).toFixed(1);
  const ssim = Math.max(0.3, (0.98 - blurAmount * 0.03)).toFixed(2);

  updateMetricsUI(sizeRatio, psnr, ssim, 100 - (blurAmount*5));
}

// ==========================================
// 7. UI Updates and Timers (General)
// ==========================================
function updateMetricsUI(sizeRatio, psnr, ssim, qualityVal) {
  sizePercentage.innerText = `${sizeRatio}%`;
  progressBarFill.style.width = `${sizeRatio}%`;

  psnrDisplay.innerText = `PSNR: ${psnr} ${psnr !== "Infinity" ? 'dB' : ''}`;
  ssimDisplay.innerText = `SSIM: ${ssim}`;

  // Calculate Game Score
  let score = 1000 + (100 - sizeRatio) * 15 - (100 - qualityVal) * 10;

  if (currentMode === 'rle') {
    // In RLE mode, penalize score based on time elapsed to encourage speed
    score = 1000 + (100 - sizeRatio) * 15 - (secondsElapsed * 5);
  }

  if (score < 0) score = 0;
  scoreDisplay.innerText = Math.floor(score);

  if (currentMode === 'compression' || currentMode === 'dct') {
    if (sizeRatio > 80) feedbackMsg.innerText = "File is still very large. Try compressing more!";
    else if (sizeRatio < 30 && psnr < 25) feedbackMsg.innerText = "Careful! Quality is dropping too low.";
    else feedbackMsg.innerText = `Great balance! You saved ${100 - sizeRatio}% file size.`;
  }
}

// Timer Controls
document.getElementById('start-btn').addEventListener('click', startGame);
document.getElementById('pause-btn').addEventListener('click', pauseGame);
document.getElementById('restart-btn').addEventListener('click', restartGame);

function formatTime(totalSeconds) {
  const m = Math.floor(totalSeconds / 60).toString().padStart(2, '0');
  const s = (totalSeconds % 60).toString().padStart(2, '0');
  return `${m}:${s}`;
}

function startGame() {
  // Allow RLE mode to bypass the image upload requirement
  if (currentMode !== 'rle' && !originalImage) {
    alert("Please upload an image first!");
    return;
  }
  if (!isPlaying) {
    isPlaying = true;
    gameTimer = setInterval(() => {
      secondsElapsed++;
      timeDisplay.innerText = formatTime(secondsElapsed);

      // Real-time score decay for RLE mode
      if (currentMode === 'rle') {
        let currentScore = parseInt(scoreDisplay.innerText);
        if (currentScore > 0 && secondsElapsed % 2 === 0) { // Decay score every 2 seconds
          scoreDisplay.innerText = currentScore - 10;
        }
      }
    }, 1000);
  }
}

function pauseGame() {
  isPlaying = false;
  clearInterval(gameTimer);
}

function restartGame() {
  pauseGame();
  secondsElapsed = 0;
  timeDisplay.innerText = "00:00";
  if (originalImage || currentMode === 'rle') {
    switchMode(currentMode);
    if (currentMode !== 'rle') startGame();
  }
}